name: Deployment DockerHub Image Push

on:
  workflow_run:
    workflows: ["Deployment Trivy File System Scan, Unittests and Release Tag"]
    types:
      - completed

jobs:

  dockerhub-image-push:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: oislen/msc-esc:latest
          build-args: GIT_BRANCH=main

  trivy-image-scan:
    needs: dockerhub-image-push
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        trivy-image-ref: oislen/msc-esc:latest
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'