name: Deployment Trivy File System Scan

on:
    workflow_run:
      workflows: ["Deployment DockerHub Image Push"]
      types:
        - completed

jobs:
  fs-scan:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: oislen/msc-esc:latest
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'
