name: Development Trivy File System Scan

on:
  pull_request:
    branches: [ dev, main ]

jobs:
  fs-scan:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run Trivy vulnerability scanner in fs mode
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        trivy-config: trivy.yml
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
