name: Development Workflow

on:
  pull_request:
    branches: [ dev, main ]

jobs:

  trivy-fs-scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Run Trivy vulnerability scanner in fs mode
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        exit-code: '1'

  r-unittests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Run Trivy vulnerability scanner in fs mode
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        trivy-config: trivy.yml
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
    - name: Setup R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.4.2'
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev libfontconfig1-dev
    - name: Install R dependencies
      run: |
        Rscript -e 'install.packages(c("renv", "pak"), repos = "https://cloud.r-project.org")'
    - name: Restore R environment
      shell: Rscript {0}
      run: |
        options(repos = c(CRAN = "https://cran.rstudio.com/"))
        options(renv.config.pak.enabled=TRUE)
        Sys.setenv(RENV_CONFIG_PAK_ENABLED=TRUE)
        renv::restore()
    - name: Execute R Testthat Unittests
      shell: Rscript {0}
      run: |
        renv::load()
        testthat::test_dir('./scripts/utilities/unittests')